from __future__ import annotations

from functools import lru_cache
from typing import Optional

from cryptography.fernet import Fernet
from pydantic import SecretStr

from promopulse.core.config import get_settings


class EncryptionService:
    """
    Thin wrapper around cryptography.Fernet for PII encryption.

    - Uses a single symmetric key (Fernet).
    - Provides simple string in → string out encrypt/decrypt methods.
    """

    def __init__(self, key: str | bytes) -> None:
        if isinstance(key, str):
            key_bytes = key.encode("utf-8")
        else:
            key_bytes = key

        # Fernet will validate the key format here and raise on invalid.
        self._fernet = Fernet(key_bytes)

    def encrypt(self, value: Optional[str]) -> Optional[str]:
        """
        Encrypts a string and returns a base64-encoded ciphertext string.
        Returns None if value is None.
        """
        if value is None:
            return None

        token = self._fernet.encrypt(value.encode("utf-8"))
        return token.decode("utf-8")

    def decrypt(self, value: Optional[str]) -> Optional[str]:
        """
        Decrypts a previously encrypted string and returns the plaintext.
        Returns None if value is None.
        """
        if value is None:
            return None

        plaintext_bytes = self._fernet.decrypt(value.encode("utf-8"))
        return plaintext_bytes.decode("utf-8")


@lru_cache
def get_encryption_service() -> EncryptionService:
    """
    Returns a cached EncryptionService instance.

    - Reads PII_ENCRYPTION_KEY from settings.
    - Fails fast with a clear RuntimeError if the key is missing or invalid.
    """
    settings = get_settings()
    key_secret: SecretStr | None = settings.pii_encryption_key

    if key_secret is None:
        raise RuntimeError(
            "PII_ENCRYPTION_KEY is not configured. "
            "Set a valid Fernet key (urlsafe base64 32-byte) in the environment."
        )

    key = key_secret.get_secret_value()

    try:
        return EncryptionService(key)
    except (ValueError, TypeError) as exc:
        raise RuntimeError(
            "PII_ENCRYPTION_KEY is invalid. It must be a URL-safe base64-encoded "
            "32-byte key generated by cryptography.Fernet."
        ) from exc
