"""add users table

Revision ID: 652e60e2bfd9
Revises: 20241208_0001
Create Date: 2025-12-08 16:03:27.343006

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '652e60e2bfd9'
down_revision = '20241208_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
